Lab3
intade/PPO pull request #4
Opened 2020-12-10 16:27 UTC by intade

2020-12-14 15:11 UTC, gmltA requested changes
I don't think you have a Gravatar implementation, do you?

2020-12-14 16:02 UTC, intade commented
sorry, i misundertood the task. I've added the gravatar

2020-12-14 16:10 UTC, gmltA reviewed
I don't see how are you checking which avatar provider should be used for the user...

2020-12-17 15:00 UTC, gmltA approved these changes
Okay. Good luck!

2020-12-17 15:34 UTC, merged